### PR TITLE
feat: add `README.md` on each stdlib folder

### PR DESCRIPTION
**Pull request by The-Lum**
Hello plantuml-stdlib team,

To follow:
- #102

Here is a PR in order to add a `README.md` on each stdlib folder.

I understand that is redundant with INFO, but it is easier to navigate and that is automatically display by GitHub.

_Open to discussion,..._
Regards,
Th.

### CODE REVIEW

**Comment by arnaudroques** [comment]
> I understand that is redundant with INFO, but it is easier to navigate and that is automatically display by GitHub.

Actually, that’s a great idea! We could take it a step further by removing the INFO files altogether. Instead, we can [update the code](https://github.com/plantuml/plantuml-stdlib/blob/f0da00ac172c6fd22934318ad425d251b9429f72/src/main/java/com/plantuml/stdlibencoder/StdlibFolderBuilder.java#L120) to read the necessary information from the README.md files, eliminating the need for INFO files.

How does that sound? I'll handle the Java code modification—it should be a straightforward change.

**Comment by The-Lum** [comment]
Hello @arnaudroques,

Otherwise I can suggest this new version _(And I can make a new PR)_ which is between the INFO and the Simple Markdown, the Markdown with YAML frontmatter, as:

```md
---
version: x.y.z
source: https://github.com/URL
link: xxx
author: authors_names
---

# Information about `stdlib/XXX`

Other info. for human... displayed by GH...
```

Open to discussion,
_That seems better that markdown table, and for java parsing that seems better... ? No?_
_And this could also be useful for the PlantUML Theme gallery..._

_[FYI @Potherca, @kirchsth, @boessu, @theavege, @johthor]_

**Comment by kirchsth** [comment]
Hi all,

What is the goal of the library specific readme.md file?
For me it could be 

1) a standardized format, that we can combine all  lib-specific readme.md (and info.txt) to the overall readme.md in a standardized way.
2) but additional it would be nice, that the info.txt (and parts of readme.md) can be directly used in the plantuml-diagrams. 
   `%stdlib-info("C4")` could create a note with markdown
   `%stdlib-json("C4")` could return the info as json
   `%stdlib-readme("C4")` could return the short description of the json
   
   and if the functions are called ex. without an argument, all possible standard libraries are returned.  

**Library-specific Readme.md**

```markdown
The C4 library enables a simple way of describing and communicate software architectures with an intuitive language.

It is the PlantUML integrated version of [C4-PlantUML](https://github.com/plantuml-stdlib/C4-PlantUML) and has the big advantage that it can be used without additional external includes.
(E.g. container diagrams can be drawn with `!include <C4/C4_Container>` and no `!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml` is required.)

Example of usage:

```plantuml
@startuml
!include <C4/C4_Container>
LAYOUT_LEFT_RIGHT()

Person(admin, "Administrator")
System_Boundary(c1, "Sample System") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")

SHOW_LEGEND()
@enduml
```plantuml

This example renders the following image:

[![Example](https://www.plantuml.com/plantuml/png/JL1TQy9047o_Nx5DNn8GYyN7KanJgmMhOivAdyAPRE7WFiBT1f7I_zvDjTfxMUvcPcTk9f5KeCuQSQDTRRe6uQ4OtnNZgl2Eb7OO7iKY_rXjPRMOliXgypgRopGJOeqXUfUgncetW2JlfuuK5FcGPA8yHa9RFVdEDIeSqth4f5BPrY2Si2I3Bm5yBaxf0VULQbjcxd0FUTiQNIlItYNyLDmE82_Nm-LKiYGWt0z7yFPUz5XkZ3z4w2A62EIXzhPLJB6T8TrRoeCcmW2aBHhsYXpn-nmofHF8Uyuq1iK6pT_dhh6saPKyvrAkooJx9LtGwvePKkGhzkCpUFjV8ihvQiTTpgRBP-vnWgxX-dy0)](https://www.plantuml.com/plantuml/uml/JL1TQy9047o_Nx5DNn8GYyN7KanJgmMhOivAdyAPRE7WFiBT1f7I_zvDjTfxMUvcPcTk9f5KeCuQSQDTRRe6uQ4OtnNZgl2Eb7OO7iKY_rXjPRMOliXgypgRopGJOeqXUfUgncetW2JlfuuK5FcGPA8yHa9RFVdEDIeSqth4f5BPrY2Si2I3Bm5yBaxf0VULQbjcxd0FUTiQNIlItYNyLDmE82_Nm-LKiYGWt0z7yFPUz5XkZ3z4w2A62EIXzhPLJB6T8TrRoeCcmW2aBHhsYXpn-nmofHF8Uyuq1iK6pT_dhh6saPKyvrAkooJx9LtGwvePKkGhzkCpUFjV8ihvQiTTpgRBP-vnWgxX-dy0)

```

**Library-specific Info.json**

```json
{
   "Name": "C4 library (C4-PlantUML)",
   "Version" : "2.11.0",
   "Optional Link to concrete Version/Release": "https://github.com/plantuml-stdlib/C4-PlantUML/tree/release/v2.11.0",
   
   "Source": "https://github.com/plantuml-stdlib/C4-PlantUML",
   "ShortDescription(as simple markdown)": ""
   "Authors":"",
   "License":"" 
   ...
}
```

**Generated part of overall README.md**

```markdown

=={Name from info.json} [{folder name}]     ....  C4 library (C4-PlantUML) [C4]

{Values from Info.json (as table, badges or mixed?)}

{Library-specific Readme.md}
```

**output of %stdlib-info("C4")**

format is not correct, links not working,... but the idea should be clear 
```plantuml
@startuml
rectangle StdLibInfoC4 <<stdlibinfo>> [
| Folder(?)  | C4 |
| Name    | **C4 library (C4-PlantUML)** |
| Version | [**2.11.0**](https://github.com/plantuml-stdlib/C4-PlantUML/tree/release/v2.11.0) |
| Source  | [https://github.com/plantuml-stdlib/C4-PlantUML](https://github.com/plantuml-stdlib/C4-PlantUML)|
| Authors | Ricardo Niepel, ... |
| License | MIT |

**Short description** 

The C4 library enables a simple way of describing and communicate software architectures with an intuitive language.
It is the PlantUML integrated version of [C4-PlantUML](https://github.com/plantuml-stdlib/C4-PlantUML) and has the big advantage that it can be used without additional external includes.
(E.g. container diagrams can be drawn with `!include <C4/C4_Container>` and no `!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml` is required.)
]
@enduml
```

**output of %stdlib-json("C4")**

```json
{info.json as json, that it can be directly used in plantuml}
```

**output of %stdlib-readme("C4")**

```plantuml
{"ShortDescription(as simple markdown)" value of info.json, that it can be directly used in plantuml}
```

**Comment by The-Lum** [comment]
Hi all,

With:
- #115 

Here is a proposal `README.md` file format in order to replace `INFO` file:
```md
---
name: <stdlib_name>
display_name: <display_name>
author: <author>
version: x.y.z
source: <URL>
origin: 
---

Information about the `XXX` Standard Library.

```

Regards,
Th.

**Comment by kirchsth** [comment]
it could be that the output of %stdlib-info("C4") returns too much information. C4-PlantUML support following calls:

- `C4Version()`: returns only version number of C4
- `C4VersionDetails()`: creates a rectangle with the version number of PlantUML and C4

[](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuLBCp4lEAKr9LR1nDj5tDj4h00hQSN7b92QbvYWucuIb5XLdvkTfQ79nmJakgIM9cJd5834kXzIy5A0E0000)

**Comment by Potherca** [comment]
> As a consumer of the `INFO` files (for instance in [plantuml-stdlib/update-stdlib.sh](https://github.com/plantuml-stdlib/update-stdlib.sh)), I definitely prefer YAML frontmatter over MD tables.
> 
> On the topic what should be in the file, I am still unsure. The `README.md` already in the projects themselves would not translate well into plantuml/plantuml-stdlib.
> 
> So what information should be present in the README and where should it come from?


https://github.com/plantuml/plantuml-stdlib/discussions/102#discussioncomment-11255064

**Comment by The-Lum** [comment]
Hi all,

With:
- #116

Here is a new proposal `README.md` file format in order to replace `INFO` file:
```md
---
name: <stdlib_name>
display_name: <display_name>
description: <desc>
author: <author>
release: <release URL>
license: <lic>
version: x.y.z
source: <URL>
origin: 
---

Information about the `XXX` Standard Library.

```

Regards,
Th.

**Pull request merged**
