### PR TITLE
fix all.json and all.puml for awslib and azure and fix k8s

### PR DESCRIPTION
**Pull request by theavege**
#97

### CODE REVIEW

**Comment by The-Lum** [comment]
Hi @theavege,

Thanks;
Beware of the JSON:
- Now if you use Array, the delimiter will be `[` and `]`.

Regards,
Th.

**Comment by The-Lum** [comment]
@theavege

As mentioned on a remark on the code:
- Why k8s/Container.puml, k8s/Context.puml are deleted?

There are now include on the Common file?
But, we must now change the examples...

- Could you give some further explanations?

_[FYI @arnaudroques]_
Regards,
Th.

**Comment by theavege** [comment]
@The-Lum 

> Why k8s/Container.puml, k8s/Context.puml are deleted?
Container.puml and Context.puml crossed paths with C4 and were useless.

> But, we must now change the examples...

What examples should I correct?

**Comment by The-Lum** [comment]
Hi @theavege,

> Container.puml and Context.puml crossed paths with C4 and were useless.

We see that `Context.puml` is now at the end of `Common.puml`?

But for `Container.puml` I don't know.

>What examples should I correct?

And for the example, is it on the `readme`:
https://github.com/plantuml/plantuml-stdlib/blob/f6ca5fe19fbbe2a63cce524674d8c12cbefd1fc2/README.md?plain=1#L386-L391

Copy from:
- https://github.com/dcasati/kubernetes-PlantUML/blob/master/samples/hello-world.puml

_I'm currently looking for minimum examples for each stdlib._

_[FYI @arnaudroques]_
Regards,
Th.

**Comment by theavege** [comment]
> We see that Context.puml is now at the end of Common.puml?

True

> But for Container.puml I don't know.

Container.puml  was useless.

**Pull request merged**
